version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Australia/Melbourne
    open-pull-requests-limit: 3
    groups:
      npm-minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
      - dependency-name: prettier
      - dependency-name: prettier-plugin-svelte
      - dependency-name: prettier-plugin-tailwindcss

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:30'
      timezone: Australia/Melbourne
    open-pull-requests-limit: 3
